SELECT H.HACKER_ID, H.NAME, SUM(SCORE)
FROM HACKERS H INNER JOIN (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS SCORE
    FROM SUBMISSIONS 
    GROUP BY HACKER_ID, CHALLENGE_ID) T 
    ON T.HACKER_ID = H.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(SCORE) > 0
ORDER BY SUM(SCORE) DESC, HACKER_ID ASC;
