SELECT W.ID, WP.AGE, H.COINS_NEEDED, H.POWER
FROM (SELECT CODE, POWER, MIN(COINS_NEEDED) AS COINS_NEEDED FROM WANDS GROUP BY CODE, POWER) AS H
JOIN Wands AS W ON H.code = W.code AND H.power = W.power AND H.coins_needed = W.coins_needed
JOIN Wands_Property AS WP ON H.code = WP.code
WHERE WP.IS_EVIL = 0
ORDER BY H.POWER DESC, WP.AGE DESC;
