SELECT MIN(DOCTOR), MIN(PROFESSOR), MIN(SINGER), MIN(ACTOR)
FROM (
    SELECT ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS ROWNUM,
        CASE 
            WHEN OCCUPATION = 'DOCTOR' THEN NAME 
        END DOCTOR,
        CASE 
            WHEN OCCUPATION = 'PROFESSOR' THEN NAME 
        END PROFESSOR,
        CASE 
            WHEN OCCUPATION = 'SINGER' THEN NAME 
        END SINGER,
        CASE 
            WHEN OCCUPATION = 'ACTOR' THEN NAME 
        END ACTOR
    FROM OCCUPATIONS
) O
GROUP BY ROWNUM
